# Generated by Django 3.0.4 on 2020-03-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontPage_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerlocation',
            name='addr',
        ),
        migrations.AddField(
            model_name='customerlocation',
            name='postcode',
            field=models.IntegerField(default=1000),
        ),
    ]
